### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by MoOx** [jxnblk/blog#1]
Why don't you use the [`browsers` option](http://cssnext.io/usage/#browsers) of cssnext instead of disabling some features by hand ?

**Comment by jxnblk** [comment]
I try not to write CSS based on browser support, but instead stick to what's in the specification.

The two features I disable are somewhat opinionated and don't work well with Basscss:
1. colorRgba converts the `--darken-1` through `--darken-4` values to straight black, when actually they are closer to white.
2. I'd rather have rem units not picked up in older browsers than have px fallbacks.
