### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by joryphillips** [jxnblk/blog#12]
Great tutorial! After stumbling onto Basscss after finding Plangular, I decided to give this a go as well. I managed to reshape my personal website using this as a base. I went a bit further and added CSS transitions in the routing, but need to do some work to make it perform better and more logically with touch events on mobile.

You're doing great work. Also of note: you were mentioned at the Jquery conference yesterday when CSS Stats was shown on a slide.  

One quick note for the tutorial is that I had to specifically add cssnext itself to get cssnext-loader to work:
`npm i --save-dev basscss css-loader cssnext cssnext-loader`  
And a question, have you gotten the react hot loader to work with this setup?

**Comment by jxnblk** [comment]
Thanks! I really enjoyed the mod-ular CSS talk.

I'm not sure why you'd need to also install the `cssnext` standalone module, and I haven't yet tried hot loading with this approach, but will look into it.
