### ISSUE TITLE
Hamburgers & Basements: Why Not to Use Left Nav Flyouts

### ISSUE THREAD

**Issue by hew** [jxnblk/blog#13]
Others have said a similar thing: why hide content? I think that question is certainly pertinent. 

However, in 2015, hasn't the hamburger come to stand for 'this is the button for hidden content'? It has a kind of culturally appropriated meaning now, for better or for worse. Which somewhat begs the question of whether or not hiding content is all that bad **if the user knows its there**?

**Comment by jxnblk** [comment]
Did you read the follow up article? http://jxnblk.com/writing/posts/an-update-on-the-hamburger-menu/

Generally this article isn't about just the hamburger menu, but all interaction patterns. The hamburger still has the same issues that it's always had, and I don't think hiding global navigation behind a progressive disclosure mechanism will ever be a useful pattern.

As for awareness of the menu, I have never seen it perform well in user research.
