### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by albacoretuna** [jxnblk/blog#16]
Thanks for the clear write up! I'm in the process of changing a wordpress website into a static one, due to security, maintenance and speed problems, I think this is too much for 10 static pages, but anyway it was eyeopening. 

Omid

**Comment by lachlanjc** [comment]
@omidfi React is awesome, but for a blog I’d probably not recommend it — however, you should definitely check out [Jekyll](http://jekyllrb.com/).

**Comment by jxnblk** [comment]
@omidfi you're welcome :sunglasses:

As for the move from Wordpress to a static site, that's a great move and should help you avoid a lot of security issues. And if the React/webpack thing is too complex, +1 to Jekyll.
