### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by koistya** [jxnblk/blog#18]
An alternative solution is to generate static website pages and routing based on the list of React components in a specific folder. For example:

```
/src/app.js
/src/components/*.js
/src/pages/index.js
/src/pages/articles/index.js
/src/pages/articles/some-article.js
```

will be compiled into

```
/build/app.js                        - common chunk of the application bundle (code splitting)
/build/index.html                    - pre-rendered HTML page (good for SEO)
/build/index.js                      - an additional chunk just of the index.html page
/build/articles/index.html
/build/articles/index.js
/build/articles/some-article.html
/build/articles/some-article.js
```

And the compiled application bundle will contain all the routing information for these pages.

`app.js` will contain only common chunk of the application bundle, and when user browsers the site additional chunks are loaded asynchronously so the site works as SPA and at the same time you don't load everything upfront into the browser.

Here is an example: https://github.com/koistya/react-static-boilerplate

---

Follow me on [Twitter](https://twitter.com/koistya) or [GitHub](https://github.com/koistya)

**Comment by jxnblk** [comment]
Thanks! I really like the `react-router` API, and v1 seems to be even better. Also, I think for most of my cases, loading and caching the full JS bundle up front is the better approach for performance.
