### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by jarodtaylor** [jxnblk/blog#19]
Love this tutorial, but I'm running into issues due to the newest [react-router 1.0.0](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md). 

I'm still new to React, so I'm trying to figure out how to re-write this part, but with react-router 1.0.0:

```
// entry.js
var React = require('react')
var Router = require('react-router')
var Routes = require('./Routes.jsx')

module.exports = function render(locals, callback) {
  Router.run(Routes, locals.path, function (Handler) {
    var html = React.renderToStaticMarkup(React.createElement(Handler, locals))
    callback(null, '<!DOCTYPE html>' + html)
  })
}
```

Their docs just show that you use `React.render(<Router routes={routes}/>, el)` but I'm not sure if the React.render callback function is going to function like the Handler you use in your write-up. 

Sorry, if this is a dumb question. I just can't seem to find anything online to help.

**Comment by jxnblk** [comment]
Yeah, I dabbled with react-router 1.0 a little and ended up using this plugin for static site generation: https://github.com/qimingweng/static-render-webpack-plugin

I plan on making an updated boilerplate, but haven't gotten around to it yet.
