### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by aputinski** [jxnblk/blog#2]
Thanks for writing an article about this — really awesome topic. I've been going through the process of creating a fairly large static React site and had a few observations.

The `static-site-generator-webpack-plugin` is pretty awesome, but I ended up not using it for a few reasons:

Currently it doesn't work with the `webpack.optimize.CommonsChunkPlugin`, so this means that `bundle.js` will get quite large depending on the number of pages on your website. In my experience, the primary difference between single page apps and static sites is that static sites tend to have large amounts of code that might only be applicable on certain pages. That being said, it's unfortunate that a user has to incur the cost of downloading `bundle.js` for a page that could have only a single paragraph of text.

Another advantage of statically rendered sites that is lost with this approach is download speed.

``` jsx
<body className='p2'>
  <Header />
  <RouteHandler {...this.props} />
  <script
    id='initial-props'
    type='application/json'
    dangerouslySetInnerHTML={initialProps} />
  <script src='bundle.js' />
</body>
```

If the props are just a few strings it's not a huge deal, but if the props contain complex JSON objects, the user has to download a large chunk of data in the initial payload which can't be utilized until `bundle.js` is downloaded.

Due to the issue above, the user is downloading two copies of the critical css on each payload — once in a `<style />` tag and once in a `<script />` tag.

Finally, because the webpack `entry` needs to be run in node as well, a good deal of webpack functionality is lost — any `resolve` configurations, `CommonsChunkPlugin`, and a few others.

The code I ended up writing to avoid these issues isn't as pretty as the approach described in your post, but now that I have the final output I want, I'm hoping I can optimize the build code.

Let me know if you have any thoughts on some of these issues — I probably spent way to long trying to solve some of them :)

**Comment by jxnblk** [comment]
Thanks, this is helpful.

I tried to mention some of the caveats with the JSON part, but maybe I should emphasize it more. I realized (I think) a better way to handle the CSS using css-loader and cssnext-loader and am planning on updating the post.

As for generally keeping the static-rendered and client-side props in sync, do you have any better suggestions?

Also I'd love to see a link to what you have if it's public.

**Comment by aputinski** [comment]
So the approach I'm taking looks something like this:

``` jsx
class Page extends React.Component {
  render() {
    return (
      <html lang="en">
        {this.renderHead()}
        {this.renderBody()}
      </html>
    );
  }
  renderHead() {
    return (
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <title>{this.props.title}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {this.renderStyles()}
      </head>
    );
  }
  renderBody() {
    return (
      <body>
        {this.renderScripts()}
      </body>
    );
  }
}
```

I then have a `<PageBody />` component that is used to construct each page — so an example page on my site might look like:

``` jsx
import React from 'react'
import PageBody from 'components/page/body'
export default (
  <PageBody>
    <p>Hello World</p>
  </PageBody>
)
```

When I go through the static rendering process, I render the `<Page />` component using `React.renderToStaticMarkup()` and the `<PageBody />` using `React.renderToString()`. I then inject the react markup into the `<body />` of the static markup. By doing this, I'm only forced to reconstruct the `<PageBody />` client-side, which means I don't need to send down the critical CSS twice.

**Comment by jxnblk** [comment]
Oh yeah that makes sense. I've been interested in conditionally loading all the CSS per page based on components, and I think that's why I've been doing the full document.

I'm still not sure I understand how you're keeping static and client props in sync, but maybe I'm missing something.

**Comment by aputinski** [comment]
I'm doing something very similar to what you described where I `JSON.stringify()` the props for the client, I'm just offloading the result to a separate file so that the page loads quicker and then once the necessary `.js` files have been downloaded React can rehydrate the client. I'm doing this primarily because I know that my stringified props will be fairly large.

**Comment by jxnblk** [comment]
Ah thanks, this is super helpful. I did update the post to reflect using webpack to handle the CSS, so the duplication of that shouldn't be an issue anymore.
:sunglasses:
