### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by connor11528** [jxnblk/blog#20]
Hi there, Thanks for the tutorial! When using the `safeStringify` function I got:

```
ERROR in TypeError: Converting circular structure to JSON
```

**Root.jsx**

```
var React = require('react');
var Router = require('react-router');
var RouteHandler = Router.RouteHandler;
var Header = require('./Header.jsx');

var Root = React.createClass({
    render: function(){
        var initialProps = {
            __html: safeStringify(this.props)
        };

        return (
            <html>
                <head>
                    <title>{this.props.title}</title>
                </head>
                <body>
                    <Header />
                    <RouteHandler {...this.props} />
                    <script
                        id='initial-props'
                        type='application/json'
                        dangerouslySetInnerHTML={initialProps} />
                    <script src='bundle.js' />
                </body>
            </html>
        );
    }
});

// ERROR in TypeError: Converting circular structure to JSON
function safeStringify(obj){
    return JSON.stringify(obj).replace(/<\/script/g, '<\\/script').replace(/<!--/g, '<\\!--')
}
```

If I remove the safeStringify function and pass in `this.props` directly the app will compile and route between Index and About but throws an error in the console:

<img width="1397" alt="screen shot 2015-10-05 at 7 12 12 pm" src="https://cloud.githubusercontent.com/assets/3578908/10298544/1487d434-6b95-11e5-886e-41dcfa9077c0.png">

**entry.js**

```
// webpack will read this to build bundle.js
var React = require('react');
var Router = require('react-router');
var Routes = require('./Routes.jsx');

// only run client-side
if(typeof document !== 'undefined'){
    var initialProps = JSON.parse(document.getElementById('initial-props').innerHTML);
    Router.run(Routes, Router.HistoryLocation, function(Handler){
        React.render(React.createElement(Handler, initialProps), document);
    })
}

module.exports = function render(locals, callback){
    Router.run(Routes, locals.path, function(Handler){
        var html = React.renderToString(React.createElement(Handler, locals));
        callback(null, '<!DOCTYPE html>' + html);
    })
};
```

**Comment by heeton** [comment]
@cleechtech Very new to react + this repo, so just sharing some basic working in case it's helpful. 

The `initialProps` variable is used in the HTML snippet to create a script tag containing some JSON. The `safeStringify` method converts an object into JSON, so you've ended up inserting a raw object into the HTML instead of JSON (hence the `Unexpected token o` error). 

The reason that safeStringify is failing, is because the props object contains circular references... I think?

**Comment by heeton** [comment]
Update: removing the 'webpackStats' attribute of the props object helps, but throws a React warning about not editing the props object ;) 

I.e. 
```
  render: function () {
    this.props.webpackStats = undefined
    var initialProps = {
      __html: safeStringify(this.props)
    }
```

**Comment by alexslade** [comment]
_facepalm_ 
Sorry, accidentally put some comments here instead of https://github.com/jxnblk/react-static-site-boilerplate/issues/9. 

Blame late-night coding and too many tabs open ;)

**Comment by connor11528** [comment]
haha no worries thanks for your help

**Comment by johnbotica** [comment]
Having this same issue - any solution for this?

**Comment by alexslade** [comment]
@johnbotica Yes, https://github.com/jxnblk/react-static-site-boilerplate/issues/9
