### ISSUE TITLE
jsx-loader deprecated in favor of babel loader

### ISSUE THREAD

**Issue by ChrisRus** [jxnblk/blog#25]
Thanks for the great work on the tutorial.

I was running into some issues using all new bits from npmjs.org: parsing errors in my first root JSX that I really couldn't account for. After some digging, jsx-loader topped the suspects list. And, I see it's now been deprecated in favor of babel-loader: https://github.com/babel/babel-loader.

``` sh
npm install babel-loader babel-core babel-preset-es2015 babel-preset-react --save-dev
```

+

``` JavaScript
module: {
  loaders: [
    {
      test: /\.jsx?$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel', // 'babel-loader' is also a legal name to reference
      query: {
        presets: ['react', 'es2015']
      }
    }
  ]
}
```

... is working for me w/package.json dependencies:

``` JavaScript
  "devDependencies": {
    "babel": "^6.3.26",
    "babel-core": "^6.4.5",
    "babel-loader": "^6.2.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "static-site-generator-webpack-plugin": "^2.0.1",
    "webpack": "^1.12.11",
    "webpack-dev-server": "^1.14.1"
  }
```

**Comment by jxnblk** [comment]
Thanks, yeah I've been meaning to do a big update for the static site generation stuff with the latest and greatest packages, but just haven't found the time to do it yet.

**Comment by ChrisRus** [comment]
@jxnblk give me a shout when you get around to it. Perhaps we could collaborate - I'm building a "site assembler" - a collection of scripts that use JSON declarations sprinkled in your sources folders to build a graph, munge the routes, generate the server render + client app bundles. Also, I'm going to support collections because I want something I can use for blogging and rudimentary CMS. Did you see preact? https://github.com/developit/preact

**Comment by ChrisRus** [comment]
Closing as this isn't a bug and will show up in repo searches.
