### ISSUE TITLE
Static Site Generation with React and Webpack

### ISSUE THREAD

**Issue by juanmendes** [jxnblk/blog#26]
I'm trying to run your tutorial with the and I am getting the following warning when running the version with Routes.jsx: 
`90% optimize assetsWarning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).`

Followed by this error: `ERROR in TypeError: undefined is not a function
    at render (bundle.js:73:13)
    at tryCatcher (/Users/jmendes/gitclient/react-static-site/node_modules/static-site-generator-webpack-plugin/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback`

Does that ring any bells?

**Comment by jxnblk** [comment]
That is the warning React gives when you try to render something that's not a component. Have you made sure that all the components are being exported correctly and they're not `undefined`?
