### ISSUE TITLE
How are you passing props to the root component?

### ISSUE THREAD

**Issue by f0rr0** [jxnblk/blog#35]
I have been trying to wrap my head around this but can't seem to get it.
In `data.js`, you build the post meta-data and everything and export a data object.

How and where is that data object passed as props to any of the components you are using?
For example, I can't find anything like this:
`render() {
return <Posts posts={posts} />
}`

Has this got something to do with `data` being passed to the plugin:
`new StaticSiteGeneratorPlugin('bundle.js', data.routes, data)`

**Comment by jxnblk** [comment]
It's using [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin), which takes data in here: https://github.com/jxnblk/writing/blob/gh-pages/webpack.config.js#L35

This is where it uses the data for post detail views: https://github.com/jxnblk/writing/blob/gh-pages/components/Root.js

And, this is where the view is defined: https://github.com/jxnblk/writing/blob/gh-pages/entry.js#L19

Probably not the sanest organization, but it worked when I first set this up.
