### ISSUE TITLE
Patterns for Style Composition in React

### ISSUE THREAD

**Issue by mix359** [jxnblk/blog#38]
Hi jnxblk and thanks for this post! It's an interesting pattern to apply to have better component :)
With this idea, one could create a js version of bootstrap!
I only want to share with you two doubts that come to my mind reading your post:
- the first is about performance: using inline css, that it's generated from js helper function, should create performance issue. For example, everytime a form with input or button is re-rendered, every input recompute the propreties with the helper function, like the shadow, margin, etc
  And this is done in the js thread, that should manage the dom. Instead, using thing like sass or less, precompute this propreties, and it's applied from a different thread of the browser, leaving the js free to compute dom or other data.

-the second doubt it's about reusability.
It's true that i can import the component and it's ready to go. But let say that I've a new project, with complete different style. I could not load the component from and external library and use it, because I can't override all the default style (like you have presented in the article). I've to create something like a variable file in bootstrap, or completely import the components in every project, like a boilerplate

Thanks again for your article
Byez Mix

**Comment by jxnblk** [comment]
Thanks for reading! I guess you may have missed where I address those issues:

> While there are many different ways to handle styling in a component-based app, make sure to pay close attention to the size of your bundle. It can be easy to create the wrong abstractions and end up with needless bloat. Some of the patterns in this article, when taken to their logical extreme, could actually harm the performance and create a degraded experience for your end users.

That said, I think the performance issues you're stating are a bit exaggerated, and you'd likely use references to not call extra functions during render.

> I’ve used inline styles here for readability and to help demonstrate how this works, but any CSS-in-JS solution can be used instead and won’t have any affect on the form component above. By keeping all styling encapsulated in this component, the rest of the application doesn’t need to know anything about the Button beyond its props API.

Depending on how you've set up the styling/CSS, you should be able to import third-party components without messing with other assets or dependencies. At least that's the point IMO.

Also, you should probably check out [Rebass](http://jxnblk.com/rebass), which uses React context for theming, if you haven't already.
