### ISSUE TITLE
Bug: #undefined url on blog post title

### ISSUE THREAD

**Issue by farskid** [jxnblk/blog#54]
## Description

When you hover on a blog post title, you can see that the URL it's showing is ending in `#undefined`. The screenshot below can show the bug in place. take a look at the URL browser shows on the left bottom of the page.

<img width="1226" alt="Screenshot 2019-04-01 at 12 06 01" src="https://user-images.githubusercontent.com/8332043/55316280-b9b48380-5476-11e9-8293-8b2b01b7bf1b.png">

However, hovering on post body will show the correct URL and clicking on the post title will navigate to the single post page.

<img width="1214" alt="Screenshot 2019-04-01 at 12 06 12" src="https://user-images.githubusercontent.com/8332043/55316388-f4b6b700-5476-11e9-8feb-c8bc0ef09cf2.png">

**Comment by jxnblk** [comment]
Thanks! I *think* it should be fixed now

**Comment by farskid** [comment]
It's fixed now 👍
