### ISSUE TITLE
Static Site Generation with React and Webpack - Issue with webpack-dev-server

### ISSUE THREAD

**Issue by dbertella** [jxnblk/blog#6]
Hi, thanks for the awesome tutorial, I'm still at the beginning, did the first scaffolding part and try to run it now. I may miss something but I'm having this issue while running npm start:
Failed at the react-static-site@1.0.0 start script 'npm run dev'.
This is most likely a problem with the react-static-site package, not with npm itself.
Tell the author that this fails on your system: npm run dev

Do you maybe know what am I missing?
Thanks

**Comment by dbertella** [comment]
Nevermind, I don't know where the issue was but I've rewritten every files from scratch and now everything is working.

**Comment by jxnblk** [comment]
Yeah sorry. Sometimes the error messaging is vague like that. I'm looking into what can be done to make that better.

**Comment by dbertella** [comment]
Cool, thanks for your time!

2015-06-11 14:20 GMT+02:00 Brent Jackson notifications@github.com:

> Yeah sorry. Sometimes the error messaging is vague like that. I'm looking
> into what can be done to make that better.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jxnblk/writing/issues/6#issuecomment-111112929.

## 

Daniele Bertella
*web designer & developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella http://it.linkedin.com/in/danielebertella/
Twitter: _denb https://twitter.com/_denb
www.danielebertella.com
