### ISSUE TITLE
Static Site Generation with React and Webpack: Rendering to Document Error

### ISSUE THREAD

**Issue by livtanong** [jxnblk/blog#7]
```
Invariant Violation: You're trying to render a component to the document but you didn't use server rendering. We can't do this without using server rendering due to cross-browser quirks. See React.renderToString() for server rendering.
```

When attempting to render to `document`. This presents a problem, because it's suggesting we render to something /inside/ the dom, be it `body` or a generic `div`. If we use a dom element as the anchor, then naturally we can't use your `Root` (the component that wraps `<html>` around all other components) for client side rendering.

**Comment by jxnblk** [comment]
It's hard to understand the issue you're encountering without a more concrete example, but you shouldn't call `React.render()` on nested elements. This tutorial shows how to handle rendering on the document, see here: http://jxnblk.com/writing/posts/static-site-generation-with-react-and-webpack/#adding-client-side-js
